import 'package:audioplayers/audioplayers.dart';

/// Plays the bundled alert sounds (`assets/sounds/`, generated by
/// `tool/generate_alert_sounds.dart`). Played by the app rather than by the
/// notification, so they're heard even when Windows Focus or macOS Do Not
/// Disturb hides notifications. Transport only, no Riverpod.
class AlertSoundService {
  final _player = AudioPlayer();

  /// [critical] picks the two-tone sound, otherwise the soft one. A new
  /// sound cuts off one still playing.
  Future<void> play({required bool critical}) async {
    await _player.stop();
    await _player.play(
      AssetSource(
        critical ? 'sounds/alert_critical.wav' : 'sounds/alert_warning.wav',
      ),
    );
  }

  Future<void> dispose() => _player.dispose();
}
