/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with a PIN */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Signed in. Also sets the `pg_session` HttpOnly cookie. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Body isn't `{"pin": "<string>"}`. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Wrong PIN. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many wrong PINs from this IP; see `Retry-After`. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed out; the cookie is cleared. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project name, and whether this client is signed in */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Column catalogue, presets, the app's table layout, thresholds, test patterns */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Config"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All projectors with telemetry, in layout order */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Projectors"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projectors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One projector */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Projector"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description No such projector. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Groups (empty → the page shows one flat list) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Groups"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active alerts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alerts"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live updates (Server-Sent Events)
         * @description `text/event-stream`; a `: ping` comment every 15 s. Events (`event:` name → `data:` JSON):
         *
         *     | Event | Data | When |
         *     |---|---|---|
         *     | `snapshot` | `SnapshotEvent` | first, on every (re)connect |
         *     | `projectors` | `Projectors` | projectors added, removed or reordered |
         *     | `projector` | `Projector` | one projector changed |
         *     | `groups` | `Groups` | groups changed |
         *     | `project` | `ProjectEvent` | another project was opened or saved under a new name |
         *     | `signedOut` | `SignedOutEvent` | the session ended (PIN changed, *Sign out all clients*, Web Access off); the stream then closes |
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "viewer" | "operator";
        Error: {
            /** @enum {string} */
            error: "bad_request" | "invalid_pin" | "locked_out" | "unauthorized" | "not_found";
            /** @description Seconds until the IP may try again (`locked_out` only). */
            retryAfter?: number;
        };
        LoginRequest: {
            pin: string;
        };
        LoginResponse: {
            token: string;
            role: components["schemas"]["Role"];
        };
        Session: {
            projectName: string;
            authenticated: boolean;
            role?: components["schemas"]["Role"];
        };
        /** @description Display strings are exactly what the app shows ('-' = not polled yet). */
        Projector: {
            id: string;
            name: string;
            ip: string;
            groupId: string | null;
            /** @description Card position on the app's canvas (px). */
            x: number;
            y: number;
            /** @enum {string} */
            connection: "connected" | "offline" | "unauthorized" | "unprotected";
            /** @enum {string} */
            power: "standby" | "turningOn" | "on" | "cooling";
            /** @enum {string} */
            shutter: "open" | "closed";
            serial: string;
            input: string;
            signal: string;
            /** @description `OTS:xx` command of the active pattern, `OTS:00` = off, null = not polled. */
            testPattern: string | null;
            runtime: string;
            lightRuntime: string;
            intakeTemp: string;
            exhaustTemp: string;
            acVoltage: string;
            /** @description 'NO ERRORS', '-' or the projector's error code. */
            errors: string;
        };
        /** @description In layout order (left→right, top→bottom). */
        Projectors: components["schemas"]["Projector"][];
        Group: {
            id: string;
            name: string;
            color: string;
        };
        Groups: components["schemas"]["Group"][];
        TempThreshold: {
            warm: number;
            hot: number;
        };
        /** @enum {string} */
        ColumnId: "connection" | "model" | "serial" | "group" | "ip" | "power" | "shutter" | "input" | "signal" | "testPattern" | "runtime" | "lightRuntime" | "intake" | "exhaust" | "voltage" | "errors";
        /** @enum {string} */
        Density: "compact" | "standard" | "comfortable";
        TableLayout: {
            columns: components["schemas"]["ColumnId"][];
            widths: {
                [key: string]: number;
            };
            sortColumn: components["schemas"]["ColumnId"];
            sortAscending: boolean;
            density: components["schemas"]["Density"];
            fitToWidth: boolean;
            groupBy: boolean;
        };
        Config: {
            projectName: string;
            role: components["schemas"]["Role"];
            /** @description Every Monitoring column, in canonical order. */
            columns: {
                id: components["schemas"]["ColumnId"];
                label: string;
                defaultWidth: number;
            }[];
            defaultColumns: components["schemas"]["ColumnId"][];
            presets: {
                name: string;
                columns: components["schemas"]["ColumnId"][];
            }[];
            minColumnWidth: number;
            layout: components["schemas"]["TableLayout"];
            thresholds: {
                intake: components["schemas"]["TempThreshold"];
                exhaust: components["schemas"]["TempThreshold"];
            };
            testPatterns: {
                code: string;
                label: string;
            }[];
        };
        /** @description Always empty until telemetry alerts (ROADMAP §4) exist. */
        Alerts: unknown[];
        SnapshotEvent: {
            projectName: string;
            projectors: components["schemas"]["Projectors"];
            groups: components["schemas"]["Groups"];
        };
        ProjectEvent: {
            name: string;
        };
        SignedOutEvent: Record<string, never>;
    };
    responses: {
        /** @description No session, or it expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
