/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with a PIN */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Signed in. Also sets the `pg_session` HttpOnly cookie. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Body isn't `{"pin": "<string>"}`. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Wrong PIN. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many wrong PINs from this IP; see `Retry-After`. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed out; the cookie is cleared. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unlock control — upgrade this session to operator with the Operator PIN
         * @description Only exists while *Allow control* is on (404 otherwise). Wrong PINs count towards the same per-IP lockout as logins.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Now operator. The session's other tabs get an `access` event. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Access"];
                    };
                };
                /** @description Body isn't `{"pin": "<string>"}`. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Wrong PIN, or no session. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description *Allow control* is off. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many wrong PINs from this IP; see `Retry-After`. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lock — back to viewer, same session
         * @description Only exists while *Allow control* is on (404 otherwise).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Now viewer. The session's other tabs get an `access` event. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Access"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description *Allow control* is off. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send an action to projectors (operator only)
         * @description Only exists while *Allow control* is on (404 otherwise). A viewer session gets 403.
         *     Lens steps to a projector whose previous step is still in flight are dropped.
         *     Logged in the app's Event Log with the source ("Web · <ip> · operator").
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActionRequest"];
                };
            };
            responses: {
                /** @description Sent; per-projector outcome. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DispatchResult"];
                    };
                };
                /** @description Not a valid action request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Viewer session. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description *Allow control* is off. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alignment mode's state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alignment"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/{op}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Drive Alignment mode (operator only)
         * @description Only exists while *Allow control* is on (404 otherwise). A viewer session gets 403.
         *     Each op calls the app's own Alignment mode, so the app's banner follows.
         *
         *     | `op` | Body | Does |
         *     |---|---|---|
         *     | `enter` | none, or `{"targets": [ids]}` — the page's selection | scope = the selection when it has 2+ projectors, else all; waits while projectors are read |
         *     | `exit` | none | restores shutters, patterns and shutter fades; waits until done |
         *     | `next` / `prev` | none | step in layout order, wrapping |
         *     | `focus` | `{"id": "…"}` | focus one projector in the scope |
         *     | `neighbours` / `diagonals` / `showAll` | none | flip the toggle |
         *     | `preset` | `{"preset": "geometry" \| "color" \| "custom"}` | switch the task (its default patterns, Custom keeps them) |
         *     | `focusedPattern` | `{"code": "OTS:xx"}` | a pattern the current preset offers |
         *     | `othersPattern` | `{"code": "OTS:xx" \| null}` | null = same as focused |
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    op: "enter" | "exit" | "next" | "prev" | "focus" | "neighbours" | "diagonals" | "showAll" | "preset" | "focusedPattern" | "othersPattern";
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Done; the new state (every page also gets an `alignment` event). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alignment"];
                    };
                };
                /** @description Unknown op, or a body it doesn't take. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Viewer session. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description *Allow control* is off. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project name, and whether this client is signed in */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Column catalogue, presets, the app's table layout, thresholds, test patterns */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Config"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All projectors with telemetry, in layout order */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Projectors"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projectors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One projector */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Projector"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description No such projector. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Groups (empty → the page shows one flat list) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Groups"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active alerts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alerts"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge alerts (operator only)
         * @description Only exists while *Allow control* is on (404 otherwise). A viewer session gets 403.
         *     Same as in the app: OSC `/pgrid/alert/acknowledged`, a returned signal clears, and the
         *     Event Log names the source ("Signal lost acknowledged (Web · <ip> · operator)").
         *     Every page gets an `alerts` event.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcknowledgeRequest"];
                };
            };
            responses: {
                /** @description Done. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AcknowledgeResult"];
                    };
                };
                /** @description Not a valid acknowledge request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Viewer session. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description *Allow control* is off. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Poll every projector now (operator only)
         * @description Only exists while *Allow control* is on (404 otherwise). A viewer session gets 403.
         *     The app's F5: one poll cycle over every projector, logged in the Event Log with the web
         *     source. Replies when the cycle has finished; the new values reach the pages as the usual
         *     `projector` events. No body.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The cycle finished. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Viewer session. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description *Allow control* is off. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live updates (Server-Sent Events)
         * @description `text/event-stream`; a `: ping` comment every 15 s. Events (`event:` name → `data:` JSON):
         *
         *     | Event | Data | When |
         *     |---|---|---|
         *     | `snapshot` | `SnapshotEvent` | first, on every (re)connect |
         *     | `projectors` | `Projectors` | projectors added, removed or reordered |
         *     | `projector` | `Projector` | one projector changed |
         *     | `groups` | `Groups` | groups changed |
         *     | `project` | `ProjectEvent` | another project was opened or saved under a new name |
         *     | `alignment` | `Alignment` | after `snapshot`, and whenever Alignment mode changes (from the app or any page) |
         *     | `alerts` | `Alerts` | after `alignment`, and whenever an alert is raised, changes, clears or is acknowledged |
         *     | `access` | `Access` | this session was unlocked / locked (in another tab too), or *Allow control* was switched |
         *     | `signedOut` | `SignedOutEvent` | the session ended (PIN changed, *Sign out all clients*, Web Access off); the stream then closes |
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One projector's Remote Preview (Server-Sent Events)
         * @description The app relays the projector's own preview feed (~1 fps JPEG): every page and the
         *     app's preview dialog share one feed per projector, opened by the first watcher and
         *     closed a few seconds after the last one leaves. Viewers can watch too.
         *     `text/event-stream`; a `: ping` comment every 15 s. Events:
         *
         *     | Event | Data | When |
         *     |---|---|---|
         *     | `status` | `PreviewStatus` | first, and whenever it changes |
         *     | `frame` | `PreviewFrame` | after `status` when an image is up, then each new image |
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description No such projector. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconnect the preview feed (the window's *Retry*)
         * @description Any signed-in page; only while a page watches this projector.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reconnecting; the stream reports the outcome. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                /** @description No such projector, or nobody watches it. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/{id}/preshow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch pre-show (operator only)
         * @description Only exists while *Allow control* is on (404 otherwise); a viewer session gets 403.
         *     Only in Standby with the feed up (`status` `live` or `notice`) and a page watching,
         *     as in the app; the stream's `preShow` / `preShowApplying` follow.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PreShowRequest"];
                };
            };
            responses: {
                /** @description Sent; the projector confirms it in a few seconds. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PreShowRequest"];
                    };
                };
                /** @description A bad body, or the projector can't take it now. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Viewer session. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description *Allow control* is off. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "viewer" | "operator";
        Error: {
            /** @enum {string} */
            error: "bad_request" | "invalid_pin" | "locked_out" | "unauthorized" | "forbidden" | "not_found";
            /** @description Seconds until the IP may try again (`locked_out` only). */
            retryAfter?: number;
        };
        LoginRequest: {
            pin: string;
        };
        LoginResponse: {
            token: string;
            role: components["schemas"]["Role"];
            controlAllowed: boolean;
        };
        Session: {
            projectName: string;
            authenticated: boolean;
            role?: components["schemas"]["Role"];
            /** @description *Allow control* is on: operator PIN login and *Unlock control* work. */
            controlAllowed: boolean;
        };
        /** @description This session's role, and whether *Unlock control* is available. */
        Access: {
            role: components["schemas"]["Role"];
            controlAllowed: boolean;
        };
        /** @description Display strings are exactly what the app shows ('-' = not polled yet). */
        Projector: {
            id: string;
            name: string;
            ip: string;
            groupId: string | null;
            /** @description Card position on the app's canvas (px). */
            x: number;
            y: number;
            /** @enum {string} */
            connection: "connected" | "offline" | "unauthorized" | "unprotected";
            /** @enum {string} */
            power: "standby" | "turningOn" | "on" | "cooling";
            /** @enum {string} */
            shutter: "open" | "closed";
            serial: string;
            input: string;
            signal: string;
            /** @description `OTS:xx` command of the active pattern, `OTS:00` = off, null = not polled. */
            testPattern: string | null;
            runtime: string;
            lightRuntime: string;
            intakeTemp: string;
            exhaustTemp: string;
            acVoltage: string;
            /** @description 'NO ERRORS', '-' or the projector's error code. */
            errors: string;
            /** @description `errors` decoded by the app's code table, in reply order; empty when healthy. */
            errorItems: components["schemas"]["ErrorItem"][];
        };
        ErrorItem: {
            /** @description `F305`, or the whole reply when it holds no code. */
            code: string;
            /** @description From the code table; null for a code it doesn't know. */
            name: string | null;
            severity: components["schemas"]["AlertSeverity"];
        };
        /** @enum {string} */
        AlertSeverity: "warning" | "critical";
        /** @description In layout order (left→right, top→bottom). */
        Projectors: components["schemas"]["Projector"][];
        Group: {
            id: string;
            name: string;
            color: string;
        };
        Groups: components["schemas"]["Group"][];
        TempThreshold: {
            warm: number;
            hot: number;
        };
        /** @enum {string} */
        ColumnId: "connection" | "model" | "serial" | "preview" | "group" | "ip" | "power" | "shutter" | "input" | "signal" | "testPattern" | "runtime" | "lightRuntime" | "intake" | "exhaust" | "voltage" | "errors";
        /** @enum {string} */
        Density: "compact" | "standard" | "comfortable";
        TableLayout: {
            columns: components["schemas"]["ColumnId"][];
            widths: {
                [key: string]: number;
            };
            sortColumn: components["schemas"]["ColumnId"];
            sortAscending: boolean;
            density: components["schemas"]["Density"];
            fitToWidth: boolean;
            groupBy: boolean;
        };
        Config: {
            projectName: string;
            role: components["schemas"]["Role"];
            /** @description Every Monitoring column, in canonical order. */
            columns: {
                id: components["schemas"]["ColumnId"];
                label: string;
                defaultWidth: number;
            }[];
            defaultColumns: components["schemas"]["ColumnId"][];
            presets: {
                name: string;
                columns: components["schemas"]["ColumnId"][];
            }[];
            minColumnWidth: number;
            layout: components["schemas"]["TableLayout"];
            thresholds: {
                intake: components["schemas"]["TempThreshold"];
                exhaust: components["schemas"]["TempThreshold"];
            };
            testPatterns: components["schemas"]["Options"];
            inputs: components["schemas"]["Options"];
            lensCalibrations: components["schemas"]["Options"];
            lensTypes: components["schemas"]["Options"];
            /** @description Alignment mode's tasks and the patterns each one offers (Custom = all). */
            alignmentPresets: {
                id: components["schemas"]["AlignmentPresetId"];
                label: string;
                patterns: string[];
            }[];
        };
        /** @enum {string} */
        AlignmentPresetId: "geometry" | "color" | "custom";
        /**
         * @description `focused` — shutter open, Focused pattern; `shown` — open with the Others
         *     pattern (a neighbour, or everyone under Show All); `closed` — shutter closed.
         * @enum {string}
         */
        AlignmentRole: "focused" | "shown" | "closed";
        /**
         * @description The app's Alignment mode — one shared session, driven from the app or any page.
         *     Preset, patterns and the neighbour options persist while the mode is off.
         */
        Alignment: {
            active: boolean;
            /** @description Entry (reading projectors) or exit (restoring them) in progress. */
            busy: boolean;
            focusedId: string | null;
            /** @description The mode's scope, projector id → role; empty while off. */
            roles: {
                [key: string]: components["schemas"]["AlignmentRole"];
            };
            preset: components["schemas"]["AlignmentPresetId"];
            focusedPattern: string;
            /** @description null = same as focused. */
            othersPattern: string | null;
            showNeighbours: boolean;
            includeDiagonals: boolean;
            showAll: boolean;
        };
        /** @description The app's choices for a control, in its order; `code` is what an action sends. */
        Options: {
            code: string;
            label: string;
        }[];
        /** @description The app's active alerts and its clock. */
        Alerts: {
            /**
             * Format: date-time
             * @description The app's time (UTC); the page measures durations against it, not its own clock.
             */
            now: string;
            /** @description In the app's display order (unacknowledged, problems before returned signals, critical, newest). */
            alerts: components["schemas"]["Alert"][];
        };
        Alert: {
            /** @description Stable while the alert lasts; what `ids` in an acknowledge request takes. */
            id: string;
            projectorId: string;
            /** @description The projector's name ('' once it was deleted). */
            projector: string;
            ip: string;
            rule: components["schemas"]["AlertRule"];
            /** @description The rule's name, e.g. "Signal lost". */
            label: string;
            /** @description The error code for `error`; '' for the other rules. */
            item: string;
            severity: components["schemas"]["AlertSeverity"];
            /** @description What the app shows large, e.g. "58 °C", "No signal on HDMI 1", "Back after 3 s". */
            value: string;
            /** Format: date-time */
            since: string;
            acknowledged: boolean;
            /**
             * Format: date-time
             * @description A Signal lost whose signal came back; it stays until acknowledged.
             */
            restoredAt: string | null;
        };
        /** @enum {string} */
        AlertRule: "offline" | "error" | "signal-lost" | "intake-temp" | "exhaust-temp";
        /** @description Exactly one way to name the alerts. */
        AcknowledgeRequest: {
            ids: string[];
        } | {
            projectorId: string;
        } | {
            rule: components["schemas"]["AlertRule"];
        } | {
            /** @constant */
            all: true;
        };
        AcknowledgeResult: {
            /** @description How many were unacknowledged and now are. */
            acknowledged: number;
        };
        RefreshResult: {
            /** @description False when a poll cycle was already running and the request waited for it. */
            polled: boolean;
        };
        SnapshotEvent: {
            projectName: string;
            projectors: components["schemas"]["Projectors"];
            groups: components["schemas"]["Groups"];
        };
        ProjectEvent: {
            name: string;
        };
        /** @description Explicit projector ids, one group, or every projector. */
        Targets: string[] | {
            group: string;
        } | "all";
        /** @enum {string} */
        LensAxis: "shiftH" | "shiftV" | "focus" | "zoom";
        /**
         * @description The fixed vocabulary the server maps to NTCONTROL (`web_actions.dart`).
         *     Lens `dir`: `+` = right / up / far / in.
         */
        Action: {
            /** @enum {string} */
            power: "on" | "off";
        } | {
            /** @enum {string} */
            shutter: "open" | "close";
        } | {
            /** @description An `OTS:xx` code from `Config.testPatterns`, or `OTS:00` for off. */
            testPattern: string;
        } | {
            /** @enum {string} */
            osd: "on" | "off";
        } | {
            /** @description A code from `Config.inputs`. */
            input: string;
        } | {
            /** @description A code from `Config.lensCalibrations`. */
            lensCalibration: string;
        } | {
            /** @description A code from `Config.lensTypes`. */
            lensType: string;
        } | {
            /** @constant */
            lens: "home";
        } | {
            lens: components["schemas"]["LensAxis"];
            /** @enum {string} */
            dir: "+" | "-";
            /** @enum {string} */
            speed: "slow" | "normal" | "fast";
        };
        ActionRequest: {
            targets: components["schemas"]["Targets"];
            action: components["schemas"]["Action"];
        };
        ProjectorRef: {
            id: string;
            name: string;
        };
        DispatchResult: {
            command: string;
            /** @description Readable command name, e.g. "Shutter Close". */
            label: string;
            ok: number;
            total: number;
            failed: components["schemas"]["ProjectorRef"][];
            /** @description Not connected (offline / auth error) — never sent. */
            skipped: components["schemas"]["ProjectorRef"][];
            /** @description The Event Log's line, e.g. "Shutter Close — 4/4 OK". */
            summary: string;
        };
        SignedOutEvent: Record<string, never>;
        PreviewStatus: {
            /**
             * @description `live` = images are coming (`frame` events); `notice` = the feed is up but the
             *     projector reports a status instead of an image; `unavailable` = no feed (offer
             *     *Retry*).
             * @enum {string}
             */
            state: "connecting" | "live" | "notice" | "unavailable";
            /** @description Set with `state` `notice`; `blank` shows nothing. */
            notice: ("noSignal" | "hdcp" | "startingUp" | "rotating" | "blank") | null;
            /** @description A tag over a live image. */
            overlay: ("testPattern" | "aspectMismatch") | null;
            /** @description The input and signal tag, e.g. "HDMI1 · 1080/60p"; null while unknown. */
            signal: string | null;
            /** @description Whether pre-show is on; null until read (only read in Standby). */
            preShow: boolean | null;
            /** @description A change was sent and the projector hasn't confirmed it yet. */
            preShowApplying: boolean;
        };
        PreviewFrame: {
            /** @description The image, base64. */
            jpeg: string;
        };
        PreShowRequest: {
            on: boolean;
        };
    };
    responses: {
        /** @description No session, or it expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
